### ISSUE TITLE
Props

### ISSUE THREAD

**Issue by kirillgenets** [Morfey216/WTW#2]
https://github.com/Morfey216/WTW/blob/4648cba8befd7574b70f211229e01e6b8946cbb2/src/components/FilmCard/FilmCard.jsx#L5-L10
Можно и стоит сократить вот так:
`
const FilmCard = ({
    name,
    previevImg,
    previevLink,
  })
`
По крайней мере мы так делаем)

**Comment by Morfey216** [comment]
ок
